### ISSUE TITLE
建议设置黑名单TOKEN可自定义KEY

### ISSUE THREAD

**Issue by yudan215** [gogf/gf-jwt#25]
目前gf-jwt默认是将md5(token)作为KEY，建议可以加KEY前缀，自定义KEY等

**Comment by yudan215** [comment]
还有最好能区分TOKEN是失效了还是已经进入黑名单，可以做不同区分
目前不管是TOKEN无效，还是TOKEN失效等等，都只有message区分，状态码一直是401，
是否可提供自定义状态码等方法？

**Comment by mingzaily** [comment]
已支持自定义key前缀，至于token失效还是过期，这个不好改动，建议还是开发者自己在Unauthorized函数根据message处理
