### ISSUE TITLE
这一段代码是表示 user路径下的所有方法都需要鉴权吗？  请关闭吧，我自己测试了

### ISSUE THREAD

**Issue by arieslee** [gogf/gf-jwt#5]
首先感觉作者能够开源这么好的框架和插件给大家使用！！
我看了一下作者的DEMO
有一个疑问
`s.Group("/user").Bind("/user", []ghttp.GroupItem{
		{"ALL", "*",              authHook, ghttp.HOOK_BEFORE_SERVE},
		{"GET", "/refresh_token", auth.GfJWTMiddleware.RefreshHandler},
		{"GET", "/hello",         hello},
	})`
这一段代码是表示 user路径下的所有方法都需要鉴权吗？
然后可以自动刷新 token?

**Comment by mobailabs** [comment]
是的, user 下面都要鉴权. /refresh_token 需要手动调用.
